name: Unity Package Export & Release

on:
  push:
    branches: [main]

env:
  UNITY_VERSION: 6000.0.47f1
  PROJECT_PATH: .
  PACKAGE_NAME: Buttr.unitypackage
  EXPORT_METHOD: PackageExporter.CreatePackage

jobs:
  export:
    name: Export Package
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Unity
        uses: game-ci/unity-setup@v4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          unityLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Export Unity Package
        uses: game-ci/unity-builder@v2
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          buildMethod: ${{ env.EXPORT_METHOD }}
          targetPlatform: StandaloneWindows64 # Required but not actually used for .unitypackage

      - name: Upload Unity Package
        uses: actions/upload-artifact@v4
        with:
          name: unity-package
          path: ${{ env.PROJECT_PATH }}/${{ env.PACKAGE_NAME }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: export
    steps:
      - name: Download Unity Package
        uses: actions/download-artifact@v4
        with:
          name: unity-package
          path: package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Unity Package v${{ github.run_number }}
          body: |
            Automatically exported Unity package.
            Commit: ${{ github.sha }}
            Unity Version: ${{ env.UNITY_VERSION }}
          draft: false
          prerelease: false

      - name: Upload .unitypackage to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: package/${{ env.PACKAGE_NAME }}
          asset_name: ${{ env.PACKAGE_NAME }}
          asset_content_type: application/octet-stream
