name: PR - Unity Tests

on:
  pull_request:
    branches:
      - main
      - develop # Trigger on pull requests targeting main or develop

env:
  UNITY_VERSION: 6000.0.47f1 # <<< IMPORTANT: Set your exact Unity version here
  PROJECT_PATH: . # <<< IMPORTANT: Path to your Unity project root (e.g., ".")

jobs:
  test:
    name: Run Unity Tests on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true # Needed if you use Git LFS for large Unity assets

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Unity-Library-${{ env.UNITY_VERSION }}-${{ hashFiles(format('{0}/**',{ env.PROJECT_PATH })) }}
          restore-keys: |
            Unity-Library-${{ env.UNITY_VERSION }}-

      - name: Set up Unity
        uses: game-ci/unity-setup@v4
        with:
          unity-version: ${{ env.UNITY_VERSION }}
          unity-license: ${{ secrets.UNITY_LICENSE }} # Use your GitHub Secret

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          testMode: all # Run both EditMode and PlayMode tests
          artifactsPath: ${{ github.workspace }}/artifacts/tests
          # testResultsPath: ./artifacts/test-results.xml # Optional: Uncomment to save detailed XML
          # coverageResultsPath: ./artifacts/coverage-results.xml # Optional: Uncomment to save coverage XML

      - name: Upload Test Results Artifacts
        if: always() # Ensure this step runs even if tests fail, so results are always available
        uses: actions/upload-artifact@v4
        with:
          name: pr-test-results
          path: ${{ github.workspace }}/artifacts/tests
          retention-days: 5 # Keep PR test results for a shorter period