name: PR - Unity Tests

on:
  pull_request:
    branches:
      - main
      - develop

env:
  UNITY_VERSION: 2023.2.14f1 # <<< IMPORTANT: Set your exact Unity version here
  PROJECT_PATH: . # <<< IMPORTANT: Path to your Unity project root (e.g., ".")

jobs:
  test:
    name: Run Unity Tests on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          # FIX: Corrected path construction for hashFiles
          key: Unity-Library-${{ env.UNITY_VERSION }}-${{ hashFiles(env.PROJECT_PATH, '/**') }}
          restore-keys: |
            Unity-Library-${{ env.UNITY_VERSION }}-

      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unity-version: ${{ env.UNITY_VERSION }}
          unity-license: ${{ secrets.UNITY_LICENSE }}

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          testMode: all
          artifactsPath: ${{ github.workspace }}/artifacts/tests

      - name: Upload Test Results Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pr-test-results
          path: ${{ github.workspace }}/artifacts/tests
          retention-days: 5